import {Food} from './app/shared/models/Food';

export const baskin_foods: Food[] = [
  {
    id:'13',
    name: 'Subway Club',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['Baskin Robins'],
    stars: 5,
    imageUrl: 'assets/br/br1.jpeg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id:'14',
    name: 'Turkey Breast',
    price: 20,
    cookTime: '20-30',
    favorite: true,
    origins: ['Baskin Robins'],
    stars: 4,
    imageUrl: 'assets/br/br2.jpeg',
    tags: ['SlowFood', 'Lunch'],
  },
  {
    id:'15',
    name: 'Steak & Cheese',
    price: 5,
    cookTime: '10-15',
    favorite: false,
    origins: ['Baskin Robins'],
    stars: 5,
    imageUrl: 'assets/br/br3.jpeg',
    tags: ['FastFood', 'Hamburger'],
  },
  {
    id:'16',
    name: 'Monterey Chicken Melt',
    price: 2,
    cookTime: '15-20',
    favorite: true,
    origins: ['Baskin Robins'],
    stars: 4,
    imageUrl: 'assets/br/br4.jpeg',
    tags: ['FastFood', 'Fry'],
  },
  {
    id:'17',
    name: 'Sweet Onion Chicken Teriyaki',
    price: 11,
    cookTime: '40-50',
    favorite: false,
    origins: ['Baskin Robins'],
    stars: 3.0,
    imageUrl: 'assets/br/br5.jpeg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    id:'18',
    name: 'Spicy Italian',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['Baskin Robins'],
    stars: 4.0,
    imageUrl: 'assets/br/br6.jpeg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id:'7',
    name: 'Subway Seafood Sensation',
    price: 12,
    cookTime: '20-30',
    favorite: false,
    origins: ['Baskin Robins'],
    stars: 4.0,
    imageUrl: 'assets/br/br7.jpeg',
    tags: ['FastFood', 'Burger', 'Lunch'],
  },
  {
    id:'8',
    name: 'Black Forest Ham',
    price: 9,
    cookTime: '45-50',
    favorite: false,
    origins: ['Baskin Robins'],
    stars: 4.0,
    imageUrl: 'assets/br/br8.jpeg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id:'9',
    name: 'Chicken & Bacon Ranch Melt',
    price: 11,
    cookTime: '40-50',
    favorite: false,
    origins: ['Baskin Robins'],
    stars: 3.0,
    imageUrl: 'assets/br/br9.jpeg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    id:'10',
    name: 'VItalian B.M.T.',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['Baskin Robins'],
    stars: 4.0,
    imageUrl: 'assets/br/br10.jpeg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id:'11',
    name: 'Pizza Sub with Cheese',
    price: 12,
    cookTime: '20-30',
    favorite: false,
    origins: ['Baskin Robins'],
    stars: 4.0,
    imageUrl: 'assets/br/br11.jpeg',
    tags: ['FastFood', 'Burger', 'Lunch'],
  },
  {
    id:'12',
    name: 'Veggie Delite',
    price: 9,
    cookTime: '45-50',
    favorite: false,
    origins: ['Baskin Robins'],
    stars: 4.0,
    imageUrl: 'assets/br/br12.jpeg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
]