import {Food} from './app/shared/models/Food';
import { Tag } from './app/shared/models/Tag';

export const sample_foods: Food[] = [
  {
    id:'1',
    name: 'Pizza Pepperoni',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['Pizza Hut'],
    stars: 5,
    imageUrl: 'assets/food-1.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id:'2',
    name: 'Meatball',
    price: 20,
    cookTime: '20-30',
    favorite: true,
    origins: ['Tim\'s Kitchen'],
    stars: 4,
    imageUrl: 'assets/food-2.jpg',
    tags: ['SlowFood', 'Lunch'],
  },
  {
    id:'3',
    name: 'Hamburger',
    price: 5,
    cookTime: '10-15',
    favorite: false,
    origins: ['Burger King'],
    stars: 5,
    imageUrl: 'assets/food-3.jpg',
    tags: ['FastFood', 'Hamburger'],
  },
  {
    id:'4',
    name: 'Fried Potatoes',
    price: 2,
    cookTime: '15-20',
    favorite: true,
    origins: ['Mac D'],
    stars: 4,
    imageUrl: 'assets/food-4.jpg',
    tags: ['FastFood', 'Fry'],
  },
  {
    id:'5',
    name: 'Chicken Soup',
    price: 11,
    cookTime: '40-50',
    favorite: false,
    origins: ['Bowl O\'China'],
    stars: 3.0,
    imageUrl: 'assets/food-5.jpg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    id:'6',
    name: 'Vegetables Pizza',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['Domino\'s'],
    stars: 4.0,
    imageUrl: 'assets/food-6.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id:'7',
    name: 'Spicy Cheese Burger',
    price: 12,
    cookTime: '20-30',
    favorite: false,
    origins: ['Burger King'],
    stars: 4.0,
    imageUrl: 'assets/food-7.jpg',
    tags: ['FastFood', 'Burger', 'Lunch'],
  },
  {
    id:'8',
    name: 'Vegetables Magento Pizza',
    price: 9,
    cookTime: '45-50',
    favorite: false,
    origins: ['Domino\'s'],
    stars: 4.0,
    imageUrl: 'assets/food-8.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id:'13',
    name: 'Subway Club',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['Baskin Robins'],
    stars: 5,
    imageUrl: 'assets/br/br1.jpeg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id:'14',
    name: 'Turkey Breast',
    price: 20,
    cookTime: '20-30',
    favorite: true,
    origins: ['Baskin Robins'],
    stars: 4,
    imageUrl: 'assets/br/br2.jpeg',
    tags: ['SlowFood', 'Lunch'],
  },
  {
    id:'15',
    name: 'Steak & Cheese',
    price: 5,
    cookTime: '10-15',
    favorite: false,
    origins: ['Baskin Robins'],
    stars: 5,
    imageUrl: 'assets/br/br3.jpeg',
    tags: ['FastFood', 'Hamburger'],
  },
  {
    id:'16',
    name: 'Monterey Chicken Melt',
    price: 2,
    cookTime: '15-20',
    favorite: true,
    origins: ['Baskin Robins'],
    stars: 4,
    imageUrl: 'assets/br/br4.jpeg',
    tags: ['FastFood', 'Fry'],
  },
  {
    id:'17',
    name: 'Sweet Onion Chicken Teriyaki',
    price: 11,
    cookTime: '40-50',
    favorite: false,
    origins: ['Baskin Robins'],
    stars: 3.0,
    imageUrl: 'assets/br/br5.jpeg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    id:'18',
    name: 'Spicy Italian',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['Baskin Robins'],
    stars: 4.0,
    imageUrl: 'assets/br/br6.jpeg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id:'19',
    name: 'Subway Club',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['Subway'],
    stars: 5,
    imageUrl: 'assets/subway/sub1.jpeg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id:'20',
    name: 'Turkey Breast',
    price: 20,
    cookTime: '20-30',
    favorite: true,
    origins: ['Subway'],
    stars: 4,
    imageUrl: 'assets/subway/sub2.jpeg',
    tags: ['SlowFood', 'Lunch'],
  },
  {
    id:'21',
    name: 'Steak & Cheese',
    price: 5,
    cookTime: '10-15',
    favorite: false,
    origins: ['Subway'],
    stars: 5,
    imageUrl: 'assets/subway/sub3.jpeg',
    tags: ['FastFood', 'Hamburger'],
  },
  {
    id:'22',
    name: 'Monterey Chicken Melt',
    price: 2,
    cookTime: '15-20',
    favorite: true,
    origins: ['Subway'],
    stars: 4,
    imageUrl: 'assets/subway/sub4.jpeg',
    tags: ['FastFood', 'Fry'],
  },
  {
    id:'23',
    name: 'Sweet Onion Chicken Teriyaki',
    price: 11,
    cookTime: '40-50',
    favorite: false,
    origins: ['Subway'],
    stars: 3.0,
    imageUrl: 'assets/subway/sub5.jpeg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    id:'24',
    name: 'Spicy Italian',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['Subway'],
    stars: 4.0,
    imageUrl: 'assets/subway/sub6.jpeg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id:'25',
    name: 'Tomatoes',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['Vegitables'],
    stars: 5,
    imageUrl: 'assets/vegitables/veg1.jpeg',
    tags: ['Vegitables'],
  },
  {
    id:'26',
    name: 'Orage Corrots',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['Vegitables'],
    stars: 5,
    imageUrl: 'assets/vegitables/veg2.jpeg',
    tags: ['Vegitables'],
  },
  {
    id:'27',
    name: 'Leafy Vegitables',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['Vegitables'],
    stars: 5,
    imageUrl: 'assets/vegitables/veg3.jpeg',
    tags: ['Vegitables'],
  },
  {
    id:'29',
    name: 'Spinach',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['Vegitables'],
    stars: 5,
    imageUrl: 'assets/vegitables/veg4.jpeg',
    tags: ['Vegitables'],
  },
  {
    id:'28',
    name: 'Chinies Cabbage',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['Vegitables'],
    stars: 5,
    imageUrl: 'assets/vegitables/veg5.jpeg',
    tags: ['Vegitables'],
  },
  {
    id:'30',
    name: 'Brocoli',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['Vegitables'],
    stars: 5,
    imageUrl: 'assets/vegitables/veg6.jpeg',
    tags: ['Vegitables'],
  },
  {
    id:'31',
    name: 'Kelloge\'s Eggo',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['Groceries'],
    stars: 5,
    imageUrl: 'assets/groceries/gro1.jpeg',
    tags: ['Groceries'],
  },
  {
    id:'32',
    name: 'Chocolate Cookies',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['Groceries'],
    stars: 5,
    imageUrl: 'assets/groceries/gro2.jpeg',
    tags: ['Groceries'],
  },
  {
    id:'33',
    name: 'Velveeta',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['Groceries'],
    stars: 5,
    imageUrl: 'assets/groceries/gro3.jpeg',
    tags: ['Groceries'],
  },
  {
    id:'34',
    name: 'Butter',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['Groceries'],
    stars: 5,
    imageUrl: 'assets/groceries/gro4.jpeg',
    tags: ['Groceries'],
  },
  {
    id:'35',
    name: 'Oreo Biscuit',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['Groceries'],
    stars: 5,
    imageUrl: 'assets/groceries/gro5.jpeg',
    tags: ['Groceries'],
  },
  {
    id:'36',
    name: 'Snyders Mini',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['Groceries'],
    stars: 5,
    imageUrl: 'assets/groceries/gro6.jpeg',
    tags: ['Groceries'],
  },
  {
    id:'37',
    name: 'Avacado',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['Fruits'],
    stars: 5,
    imageUrl: 'assets/fruits/fruit1.jpeg',
    tags: ['Fruits'],
  },
  {
    id:'38',
    name: 'Banana',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['Fruits'],
    stars: 5,
    imageUrl: 'assets/fruits/fruit2.jpeg',
    tags: ['Fruits'],
  },
  {
    id:'39',
    name: 'Dragon Fruit',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['Fruits'],
    stars: 5,
    imageUrl: 'assets/fruits/fruit3.jpeg',
    tags: ['Fruits'],
  },
  {
    id:'40',
    name: 'Fig',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['Fruits'],
    stars: 5,
    imageUrl: 'assets/fruits/fruit4.jpeg',
    tags: ['Fruits'],
  },
  {
    id:'41',
    name: 'Yellow Berries',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['Fruits'],
    stars: 5,
    imageUrl: 'assets/fruits/fruit5.jpeg',
    tags: ['Fruits'],
  },
  {
    id:'42',
    name: 'Blue Berries',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['Friuts'],
    stars: 5,
    imageUrl: 'assets/fruits/fruit6.jpeg',
    tags: ['Fruits'],
  },
  {
    id:'9',
    name: 'Chicken Soup',
    price: 11,
    cookTime: '40-50',
    favorite: false,
    origins: ['Tim\'s Kitchen'],
    stars: 3.0,
    imageUrl: 'assets/food-5.jpg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    id:'10',
    name: 'Vegetables Pizza',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['Domino\'s'],
    stars: 4.0,
    imageUrl: 'assets/food-6.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id:'11',
    name: 'Spicy Cheese Burger',
    price: 12,
    cookTime: '20-30',
    favorite: false,
    origins: ['Mac D'],
    stars: 4.0,
    imageUrl: 'assets/food-7.jpg',
    tags: ['FastFood', 'Burger', 'Lunch'],
  },
  {
    id:'12',
    name: 'Vegetables Magento Pizza',
    price: 9,
    cookTime: '45-50',
    favorite: false,
    origins: ['Domino\'s'],
    stars: 4.0,
    imageUrl: 'assets/food-8.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
]

export const sample_tags:Tag[] = [
  { name: 'All', count: 120 },
  { name: 'Groceries', count: 30 },
  { name: 'FastFood', count: 30 },
  { name: 'Pizza', count: 30 },
  { name: 'Lunch', count: 50 },
  { name: 'SlowFood', count: 20 },
  { name: 'Other', count: 10 },
  { name: 'Vegitables', count: 10 },
  { name: 'Fruits', count: 10 },
  { name: 'Ice Cream', count: 20 }
]
