import {Food} from './app/shared/models/Food';

export const subway_foods: Food[] = [
  {
    id:'19',
    name: 'Subway Club',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['Subway'],
    stars: 5,
    imageUrl: 'assets/subway/sub1.jpeg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id:'20',
    name: 'Turkey Breast',
    price: 20,
    cookTime: '20-30',
    favorite: true,
    origins: ['Subway'],
    stars: 4,
    imageUrl: 'assets/subway/sub2.jpeg',
    tags: ['SlowFood', 'Lunch'],
  },
  {
    id:'21',
    name: 'Steak & Cheese',
    price: 5,
    cookTime: '10-15',
    favorite: false,
    origins: ['Subway'],
    stars: 5,
    imageUrl: 'assets/subway/sub3.jpeg',
    tags: ['FastFood', 'Hamburger'],
  },
  {
    id:'22',
    name: 'Monterey Chicken Melt',
    price: 2,
    cookTime: '15-20',
    favorite: true,
    origins: ['Subway'],
    stars: 4,
    imageUrl: 'assets/subway/sub4.jpeg',
    tags: ['FastFood', 'Fry'],
  },
  {
    id:'23',
    name: 'Sweet Onion Chicken Teriyaki',
    price: 11,
    cookTime: '40-50',
    favorite: false,
    origins: ['Subway'],
    stars: 3.0,
    imageUrl: 'assets/subway/sub5.jpeg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    id:'24',
    name: 'Spicy Italian',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['Subway'],
    stars: 4.0,
    imageUrl: 'assets/subway/sub6.jpeg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id:'7',
    name: 'Subway Seafood Sensation',
    price: 12,
    cookTime: '20-30',
    favorite: false,
    origins: ['Subway'],
    stars: 4.0,
    imageUrl: 'assets/subway/sub7.jpeg',
    tags: ['FastFood', 'Burger', 'Lunch'],
  },
  {
    id:'8',
    name: 'Black Forest Ham',
    price: 9,
    cookTime: '45-50',
    favorite: false,
    origins: ['Subway'],
    stars: 4.0,
    imageUrl: 'assets/subway/sub8.jpeg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id:'9',
    name: 'Chicken & Bacon Ranch Melt',
    price: 11,
    cookTime: '40-50',
    favorite: false,
    origins: ['Subway'],
    stars: 3.0,
    imageUrl: 'assets/subway/sub9.jpeg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    id:'10',
    name: 'VItalian B.M.T.',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['Subway'],
    stars: 4.0,
    imageUrl: 'assets/subway/sub10.jpeg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id:'11',
    name: 'Pizza Sub with Cheese',
    price: 12,
    cookTime: '20-30',
    favorite: false,
    origins: ['Subway'],
    stars: 4.0,
    imageUrl: 'assets/subway/sub11.jpeg',
    tags: ['FastFood', 'Burger', 'Lunch'],
  },
  {
    id:'12',
    name: 'Veggie Delite',
    price: 9,
    cookTime: '45-50',
    favorite: false,
    origins: ['Subway'],
    stars: 4.0,
    imageUrl: 'assets/subway/sub12.jpeg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
]